import postgres from 'postgres';
import type { PaymentEvent } from './definitions';

/**
 * Real-time payment activity: generation + persistence + reads.
 *
 * Every simulated event is REAL — it mutates the invoices table and is
 * recorded in payment_events, so a reload shows exactly the state the events
 * produced. The SSE route (/api/events/stream) drives generatePaymentActivity
 * on a short tick while at least one signed-in client is connected, then
 * relays new payment_events rows to every connected client by id cursor.
 *
 * ── Why generation is DB-coordinated, not process-coordinated ──────────────
 *
 * On Vercel each open stream may be its own function instance, and locally
 * two tabs are two concurrent handlers. A per-process timer would multiply
 * the event rate by the number of open streams. Instead every tick runs in a
 * transaction that:
 *
 *   1. takes pg_try_advisory_xact_lock — concurrent ticks from other
 *      connections skip instead of double-generating, and
 *   2. checks the timestamp of the newest event of each type — a tick only
 *      produces an event when the cadence says one is due, no matter how many
 *      streams are ticking.
 *
 * Together these make the global rate independent of connection count, and
 * generation stops entirely when the last stream closes (nothing else calls
 * the tick). Delivery is also DB-backed: each stream keeps a last-sent id and
 * reads forward, so every client sees every event exactly once, including
 * events generated by another connection's tick, and an EventSource reconnect
 * resumes from Last-Event-ID without loss.
 */

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

// App-wide advisory lock key for the generator critical section. Arbitrary
// but fixed; only this feature uses advisory locks in this app.
const GENERATOR_LOCK_KEY = 727_272_001;

// Cadence: an outstanding invoice is paid every few seconds; a new invoice
// arrives occasionally. Timestamps of the newest event of each type are the
// clock, so the cadence holds across reconnects, restarts, and many tabs.
const PAY_EVERY_SECONDS = 4;
const CREATE_EVERY_SECONDS = 15;

// One-time, idempotent setup. payment_events is an append-only ledger of what
// the simulator did — the feed renders from it and stream cursors point into
// it. Memoized per server process; CREATE TABLE IF NOT EXISTS makes concurrent
// first-calls across processes safe.
let ready: Promise<void> | null = null;

function ensureEventsTable() {
  if (!ready) {
    ready = sql`
      CREATE TABLE IF NOT EXISTS payment_events (
        id BIGSERIAL PRIMARY KEY,
        type VARCHAR(32) NOT NULL,
        invoice_id UUID NOT NULL,
        customer_name VARCHAR(255) NOT NULL,
        customer_image_url VARCHAR(255) NOT NULL,
        amount INT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `.then(() => undefined);
  }
  return ready;
}

/**
 * One generator tick. Safe to call from any number of concurrent streams at
 * any frequency — the advisory lock serializes ticks and the cadence check
 * decides whether anything actually happens. All mutations and their event
 * rows commit atomically, so an event never exists without its invoice change
 * (and vice versa).
 */
export async function generatePaymentActivity(): Promise<void> {
  await ensureEventsTable();

  try {
    await sql.begin(async (tx) => {
      const [{ locked }] = await tx`
        SELECT pg_try_advisory_xact_lock(${GENERATOR_LOCK_KEY}) AS locked
      `;
      if (!locked) return; // another stream's tick is generating right now

      const [{ pay_due, create_due }] = await tx`
        SELECT
          NOT EXISTS (
            SELECT 1 FROM payment_events
            WHERE type = 'invoice_paid'
              AND created_at > now() - make_interval(secs => ${PAY_EVERY_SECONDS})
          ) AS pay_due,
          NOT EXISTS (
            SELECT 1 FROM payment_events
            WHERE type = 'invoice_created'
              AND created_at > now() - make_interval(secs => ${CREATE_EVERY_SECONDS})
          ) AS create_due
      `;

      if (pay_due) {
        // Pay one random outstanding invoice.
        const paid = await tx`
          WITH target AS (
            SELECT id FROM invoices WHERE status = 'pending'
            ORDER BY random() LIMIT 1
          )
          UPDATE invoices SET status = 'paid'
          FROM target WHERE invoices.id = target.id
          RETURNING invoices.id, invoices.customer_id, invoices.amount
        `;
        if (paid.length > 0) {
          const invoice = paid[0];
          const [customer] = await tx`
            SELECT name, image_url FROM customers WHERE id = ${invoice.customer_id}
          `;
          await tx`
            INSERT INTO payment_events (type, invoice_id, customer_name, customer_image_url, amount)
            VALUES ('invoice_paid', ${invoice.id}, ${customer.name}, ${customer.image_url}, ${invoice.amount})
          `;
        }
      }

      if (create_due) {
        // A new invoice arrives for a random customer, outstanding, dated today.
        const amount = Math.floor(Math.random() * 99_000) + 1_000; // cents
        const [customer] = await tx`
          SELECT id, name, image_url FROM customers ORDER BY random() LIMIT 1
        `;
        const [invoice] = await tx`
          INSERT INTO invoices (customer_id, amount, status, date)
          VALUES (${customer.id}, ${amount}, 'pending', CURRENT_DATE)
          RETURNING id
        `;
        await tx`
          INSERT INTO payment_events (type, invoice_id, customer_name, customer_image_url, amount)
          VALUES ('invoice_created', ${invoice.id}, ${customer.name}, ${customer.image_url}, ${amount})
        `;
      }
    });
  } catch (error) {
    // A failed tick is not fatal to the stream — the next tick retries.
    console.error('Payment activity generation failed:', error);
  }
}

/** Newest event id, used as the starting cursor for a fresh stream. */
export async function latestPaymentEventId(): Promise<number> {
  await ensureEventsTable();
  const [{ id }] = await sql`
    SELECT COALESCE(MAX(id), 0) AS id FROM payment_events
  `;
  return Number(id);
}

/** Events strictly after `cursor`, oldest first, bounded per read. */
export async function fetchPaymentEventsSince(
  cursor: number,
): Promise<PaymentEvent[]> {
  await ensureEventsTable();
  const rows = await sql`
    SELECT id, type, invoice_id, customer_name, customer_image_url, amount, created_at
    FROM payment_events
    WHERE id > ${cursor}
    ORDER BY id ASC
    LIMIT 100
  `;
  // BIGSERIAL comes back as a string from postgres.js; the wire format wants
  // a number so Last-Event-ID comparisons stay numeric.
  return rows.map((row) => ({
    id: Number(row.id),
    type: row.type,
    invoice_id: row.invoice_id,
    customer_name: row.customer_name,
    customer_image_url: row.customer_image_url,
    amount: row.amount,
    created_at:
      row.created_at instanceof Date
        ? row.created_at.toISOString()
        : String(row.created_at),
  }));
}
